version: '3.6'

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-shop-schedule
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
