# Generated by Django 2.1.4 on 2018-12-28 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoff',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 28, 8, 53, 11, 192976, tzinfo=utc)),
        ),
    ]
