# Generated by Django 2.1.4 on 2018-12-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20181228_1842'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='daysoff',
            index_together={('from_date', 'to_date')},
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together={('from_time', 'to_time')},
        ),
    ]
